
[tool.black]
line-length = 88
target-version = ['py37', 'py38']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.mypy_cache
    | \.tox
    | _build
    | build
    | dist
    | [^/]+/migrations  # App migrations
  )/
)
'''
[tool.coverage.run]
data_file = "demo/var/tmp/.coverage"
source = [
    "src",
]

[tool.coverage.report]
precision = 1
skip_covered = true
skip_empty = true

[tool.coverage.html]
directory = "demo/var/tmp/coverage"
skip_covered = true
skip_empty = true